[package]
name = "chat-websockets"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.24.0"
tungstenite = "0.24.0"
futures-util = "0.3.31"
askama = "0.12"